frontend:
  apiVersion: v2
  name: learner-report
  description: Helm chart for MERN application
  version: 1.0.0
  type: frontend
  image: unpredictableprashant/learnerReportCS_frontend
  tag: latest
  replicas: 3
  port: 3000
  serviceType: LoadBalancer
  servicePort: 80

backend:
  apiVersion: v2
  name: learner-report
  description: Helm chart for MERN application
  version: 1.0.0
  type: backend
  image: unpredictableprashant/learnerReportCS_backend
  tag: latest
  replicas: 3
  port: 5000
  serviceType: ClusterIP
  servicePort: 5000
  env:
    NODE_ENV: "development"
    DB_HOST: "localhost"
    DB_PORT: "27017"
